services:
  backend:
    container_name: poll-backend
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=poll-db
    depends_on:
      - db

  db:
    image: mongo
    container_name: poll-db
    command: mongod --quiet --logpath /dev/null 
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

  frontend:
    container_name: poll-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db:
